wrapperVersion=3.3.4
distributionType=only-script# Copyright (C) 2026 Gianpaolo Elias Arantes (GianArantes)
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.12/apache-maven-3.9.12-bin.zip
